### ISSUE TITLE
InsecureRequestWarning when fetching feeds

### ISSUE THREAD

**Issue by philgyford** [xurble/django-feed-reader#10]
With every feed I fetch I get this warning:

    /usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning:
    Unverified HTTPS request is being made to host 'www.example.com'.
    Adding certificate verification is strongly advised.
    See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings

I think this is because in [this line in `utils.read_feed()`](https://github.com/xurble/django-feed-reader/blob/master/feeds/utils.py#L182):

    ret = requests.get(feed_url, headers=headers, verify=False, allow_redirects=False, timeout=20, proxies=proxies)

there's `verify=False`. Given the default is `True`, I'm wondering why it's set to `False`, which generates these warnings?

**Comment by xurble** [comment]
It's because on my original hosting, many moons ago, I couldn't install client certificates to make verified requests work. 

It's probably not necessary now.

**Comment by xurble** [comment]
Fixed in next release.
