### ISSUE TITLE
Impossible to save a Source without setting last_success and last_change fields

### ISSUE THREAD

**Issue by philgyford** [xurble/django-feed-reader#11]
The `Source` model has fields like this:

```python
    last_success   = models.DateTimeField(null=True)
    last_change    = models.DateTimeField(null=True)
```

But if you're creating a `Source` in the Admin then what would you set these to, given the feed hasn't been fetched yet?

And if you create a `Source` by other means, which works, if you then want to edit the `Source` (e.g. because the Feed URL is wrong, and couldn't be fetched) then you can't save the updated version without setting these fields.

I assume they should both have `blank=True`?

**Comment by xurble** [comment]
👍
