### ISSUE TITLE
Hard-coded admin links 404 if project uses a different URL for Django Admin

### ISSUE THREAD

**Issue by philgyford** [xurble/django-feed-reader#12]
If the project has changed the URL of Django Admin from the default of `/admin/` then the two hard-coded URLs in https://github.com/xurble/django-feed-reader/blob/master/feeds/admin.py return 404s.

I think the first should use `reverse("admin:feeds_post_changelist")` and the second `reverse("admin:feeds_enclosure_changelist")`

(Sorry for the flurry of bug reports - I'm loving this app aside from these small issues!)

**Comment by xurble** [comment]
👍
