### ISSUE TITLE
Parsing a feed item with only updated dates, and no published, results in a Post with a created time of now

### ISSUE THREAD

**Issue by philgyford** [xurble/django-feed-reader#18]
Having just added a load of Sources, and fetched their feeds, I've noticed that all of their Posts had `created` times of now.

It seems that a lot of feeds have an `<updated>` date for each `<entry>` but nothing like `<published>`.

But in [these lines](https://github.com/xurble/django-feed-reader/blob/master/feeds/utils.py#L525-L530) when fetching and parsing a feed, we only look for a published date:

```python
                try:
                    p.created  = datetime.datetime.fromtimestamp(time.mktime(e.published_parsed)).replace(tzinfo=timezone.utc)
                except Exception as ex2:
                    output.write("CREATED ERROR:" + str(ex2))     
                    p.created  = timezone.now()
```

I think it would make sense that if that first attempt results in an exception we try the same thing with `e.updated_parsed` – which exists if the entry had an `<updated>` field – and only if that fails set `created` to now.

I'll do a PR for that tomorrow unless you have a better idea.

**Comment by xurble** [comment]
This was fixed but never closed
