### ISSUE TITLE
Handling longer GUIDs

### ISSUE THREAD

**Issue by llaisdy** [xurble/django-feed-reader#24]
Hello! Thanks for all your work on django-feed-reader!

Is there any reason why `models.Post.guid` has `max_length=512` (rather than eg 1024 -- I understand max_length has to be set to something)?  I am reading an rss feed which occasionally has posts with guids longer than this.  At the moment these feed posts cause an exception when `utils.parse_feed_xml()` tries to call `p.save()`.

I am wondering what the best response might be, eg:

1. increase max_length to 1024
2. truncate offending guids to max_length
3. catch the exception, discard the post and log an error

If you have a preference (I think mine would be 1 & 3), I'd be happy to submit a PR

**Comment by xurble** [comment]
This looks great.  I will try and test it this weekend and merge.  Thank you!
