### ISSUE TITLE
Missing migration for Post.guid max_size change

### ISSUE THREAD

**Issue by jonas-schuster-check24** [xurble/django-feed-reader#28]
There appears to be no new migration file added for the change to the Post model.
At least for me, when executing `python manage.py makemigrations` after updating to 1.0.8 a new migration was auto-generated.

Furthermore, applying the auto-generated migration fails with the following error message:
`django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')`

I guess `max_length` 1024 is incompatible with all DBs. 

For reference: I am using MySQL 8.0.26.

**Comment by xurble** [comment]
Apologies.  I've just released 1.0.9 to fix this.
