### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cyril36** [xurble/django-feed-reader#7]
hello,

Do you have any documentation about how to use it?
I would like to use your library to create a REST or GRAPHQL API.

Is it compatible with the latest rss and atom version?
Can i parse any type of data in the rss feed (description , title , link are probably the basic ones but if there is extra field, can i parse them?

Thank you

**Comment by xurble** [comment]
I realise that 3 years is not the fastest turnaround time in the world, but yes, there is now some [documentation](https://django-feed-reader.readthedocs.io)
